# Generated by Django 3.0.2 on 2020-11-27 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0002_free_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='free',
            old_name='contnet',
            new_name='content',
        ),
    ]
