# Generated by Django 3.0.2 on 2020-11-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0003_auto_20201127_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='free',
            name='mainphoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
